### ISSUE TITLE
Surface error(s) from fixup to API consumers

### ISSUE THREAD

**Issue by vdice** [cnabio/cnab-to-oci#103]
This is a question-request around errors that may result from various image resolving/pushing fixups as performed in `remotes/fixup.go`, specifically centering around this line: https://github.com/cnabio/cnab-to-oci/blob/master/remotes/fixup.go#L217

Currently the error appears to be logged in a debug fashion.  Is there a way for API consumers to tap into the debug logging in this case?  Or, would it make sense to immediately return the error if one occurs?

Perhaps, if a given fixup error is acceptable and the rest of the fixup functions are intended to be called, I wonder if we update the code to track/append any/all fixup errors and include this in the final returned error upon exiting the function?  (Note how no errors are wrapped in https://github.com/cnabio/cnab-to-oci/blob/master/remotes/fixup.go#L224)

A recent issue spurring these thoughts cropped up in https://github.com/deislabs/porter/issues/1032.  Here, porter utilizes this library to publish a bundle and invocation images, but currently it doesn't have visibility into any fixup errors that might occur.

**Comment by silvin-lubecki** [comment]
The current behavior has been implemented by this commit https://github.com/cnabio/cnab-to-oci/commit/534000ad0ca3e0fbcc7b459421c8d25f4bde1a22
As stated in the comment:
```
 The way `fixupBaseImage` works has been changed. Instead of having a bunch
of `if/else` a list of fixups functions is provided. Those functions are run
one after the other. If the function returns an error, then we "try" with the
next one. If the function returns a flag indicated it's OK, it means the
image has been resolved, directly or using relocation map or after a push.
Conditions (like checking the relocation map or the `pushImages` flag) are
checked inside functions.

The order is the following:

1. try to push by digest if image value is not set
2. try to resolve
3. try to resolve using the relocation map
4. try to push from local image store
```
It means that it is ok for the functions to fail and fallback to the next one.
I just checked the patch your tried https://github.com/cnabio/cnab-to-oci/compare/master...vdice:fix/fixup-return-err but I think it won't work (the Fixup fails only if all the fallbacks have been tried).

So yes there may be multiple way of getting the errors:
1/ wrap all the errors together and return them at the end
2/ connect to the logrus logger and print the debug messages. If I remember correctly that's the way we did it on docker/app: 
https://github.com/docker/app/blob/master/internal/commands/push.go#L119
https://github.com/docker/app/blob/master/internal/log/log.go#L10:1

**Comment by vdice** [comment]
@silvin-lubecki Great, thank you for the helpful context/background on this area of code.  I'll see what it looks like for Porter to connect to the logger, similar to the docker/app example provided.

**Comment by vdice** [comment]
Closing this as answered.  If for some reason option 1 above (returning multiple errors) turns out to be preferable, a PR will be opened and discussed further there.  Thanks!
